- name: switch to Google DNS
  copy: src=resolv dest=/etc/resolv.conf

#- name: fu networking
#  shell:
#    cmd: /etc/init.d/networking restart
#  args:
#    executable: /bin/bash
#  become_user: root
#  ignore_errors: yes

- name: installing alternative (dutch) apt repos
  copy: src=sources.list dest=/etc/apt/sources.list
  become_user: root

- name: install base requirements
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - ntp
    - curl
    - nload
    - build-essential
    - nmap
    - gcc
    - ngrep
    - git
    - screen
    - libssl-dev

- name: start ntp on boot
  service: name=ntp state=started enabled=yes
  when: ansible_virtualization_type != "virtualbox"

- name: stop ntp on virtualbox machines
  service: name=ntp state=stopped enabled=no
  when: ansible_virtualization_type == "virtualbox"

- name: Add PostgreSQL repository
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ jessie-pgdg main' state=present
  sudo: yes

- name: Add PostgreSQL repository key
  apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present
  sudo: yes

- name: update apt
  apt:
    update_cache: yes
